### ISSUE TITLE
.fla file given in zip is damaged, not able to make changes in look and feel

### ISSUE THREAD

**Issue by ukpatel890** [pauln/local-audio-recorder#7]
recorder.fla in src directory is damaged, can't able make changes in look, see attached screen shot,shows error when open in adobe flash 
![error](https://cloud.githubusercontent.com/assets/12195168/7530690/00bb7802-f56b-11e4-8aae-0b3f2641dd64.JPG)

**Comment by ukpatel890** [comment]
Please reply something i am waiting since 2 weeks

**Comment by pauln** [comment]
You may want to try cloning the repo or downloading the raw .fla file directly (https://github.com/pauln/local-audio-recorder/raw/master/src/recorder.fla) in case it's somehow being broken by the zip process, but I suspect that you may need a newer version of Flash in order to open it.  It opens cleanly for me in CS5.5 (which no longer provides an option to save for Flash CS3 or older - CS4 is the oldest it'll do); I can't recall which version it was last saved for, sorry.
